env:
  node: true
  es2020: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {
    'no-console': 'off',
    'import/extensions': 'off',
    "no-unused-vars": "error",
    "no-undef": "error"
}